# Generated by Django 6.0.4 on 2026-05-10 11:02

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('code', models.CharField(default=core.models.generateCode, editable=False, max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$')])),
                ('is_student', models.BooleanField(default=True)),
                ('is_assistant', models.BooleanField(default=False)),
                ('is_active_mentor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(default=core.models.generateCode, editable=False, max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$')])),
                ('description', models.TextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.category')),
                ('assistants', models.ManyToManyField(blank=True, related_name='courses_teaching', to='core.userprofile')),
                ('students', models.ManyToManyField(blank=True, related_name='courses_enrolled', to='core.userprofile')),
            ],
        ),
    ]
