# Generated by Django 6.0.4 on 2026-04-10 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$')])),
                ('description', models.TextField()),
                ('students', models.ManyToManyField(blank=True, related_name='courses', to='core.student')),
                ('teachers', models.ManyToManyField(blank=True, related_name='courses', to='core.teacher')),
            ],
        ),
    ]
