# Generated by Django 6.0.4 on 2026-04-10 13:32

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(default=core.models.generateCode, editable=False, max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='code',
            field=models.CharField(default=core.models.generateCode, editable=False, max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$')]),
        ),
    ]
