# Generated by Django 6.0.4 on 2026-04-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_surname_teacher_surname_alter_student_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
