# Generated by Django 6.0.4 on 2026-04-10 13:56

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_surname_alter_teacher_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default=core.models.generateCode, editable=False, max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$')]),
        ),
    ]
